spring:
  application:
    name: ms-books-catalogue-service
  datasource:
    url: jdbc:mysql://localhost:3306/relatosdepapel
    username: admin
    password: adminpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}::${random.value}

server:
  port: ${PORT:0}