# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=relatosdepapel
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=adminpassword

# Expose the default MySQL port
EXPOSE 3306